import sys

DISPLAY_COLUMNS = 10
DISPLAY_ROWS = 10
DISPLAY_COUNT = DISPLAY_COLUMNS * DISPLAY_ROWS

LED_COLUMNS = DISPLAY_COLUMNS
LED_ROWS = DISPLAY_ROWS
LED_COUNT = LED_COLUMNS * LED_ROWS

LED_PIN = 18

LED_TYPE = "GRB"
LED_REVERSED = True

BUTTON_A_PIN = 11
BUTTON_B_PIN = 7

BUTTON_COOLDOWN = 150  # ms
BUTTON_LONG_PRESS = 500  # ms

TEXT_GLIDING_DELAY = 40  # ms

BRIGHTNESS_HIGH = 1
BRIGHTNESS_NORMAL = 0.5
BRIGHTNESS_LOW = 0.2

DEBUG = True
MOCKED = "--mocked" in sys.argv
