import board
import neopixel

LED_COLUMNS = 10
LED_ROWS = 10

LED_COUNT = LED_COLUMNS * LED_ROWS
LED_PIXEL_ORDER = neopixel.GRB
LED_PIN = board.D18

LED_REVERSED = True

BUTTON_A_PIN = 3
BUTTON_B_PIN = 2

BUTTON_COOLDOWN = 150  # ms
BUTTON_LONG_PRESS = 500  # ms

TEXT_GLIDING_DELAY = 40  # ms

BRIGHTNESS_HIGH = 1
BRIGHTNESS_NORMAL = 0.7
BRIGHTNESS_LOW = 0.4
