FROM balenalib/%%RESIN_MACHINE_NAME%%-python

WORKDIR /usr/src/app

RUN apt-get update && apt-get install gcc python-dev

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

WORKDIR /usr/src/app
COPY . ./

CMD ["python", "os/os.py"]